import { songType } from '../../types';
import { artistNames } from './artists';

const songs: songType[] = [
  {
    id: 0,
    title: 'Ni**as In Paris',
    artists: [artistNames.jayz, artistNames.kanye],
    features: [],
    coverUrl:
      'https://bev-streams.s3.eu-central-1.amazonaws.com/african-americans-in-america/cover.png',
    songUrl:
      'https://bev-streams.s3.eu-central-1.amazonaws.com/african-americans-in-america/song.mp3',
    lyricsUrl:
      'https://bev-streams.s3.eu-central-1.amazonaws.com/african-americans-in-america/lyrics.lrc',
    duration: 232000,
  },
  {
    id: 1,
    title: 'Soul to Soul',
    artists: [],
    features: [],
    coverUrl:
      'https://bev-streams.s3.eu-central-1.amazonaws.com/soul-to-soul.jpg',
    songUrl:
      'https://bev-streams.s3.eu-central-1.amazonaws.com/soul-to-soul.mp3',
    duration: 481000,
  },
  {
    id: 2,
    title: 'Call Me Maybe',
    artists: [artistNames.carly_rae_Jepsen],
    features: [],
    coverUrl:
      'https://bev-streams.s3.eu-central-1.amazonaws.com/call-me-maybe/cover.jpeg',
    songUrl:
      'https://bev-streams.s3.eu-central-1.amazonaws.com/call-me-maybe/song.mp3',
    lyricsUrl:
      'https://bev-streams.s3.eu-central-1.amazonaws.com/call-me-maybe/lyrics.lrc',
    duration: 194000,
  },
  {
    id: 3,
    title: 'Shake It Off',
    artists: [artistNames.taylor_swift],
    features: [],
    coverUrl: '/shake-it-off/cover.png',
    songUrl: '/shake-it-off/song.mp3',
    lyricsUrl: '/shake-it-off/lyrics.lrc',
    duration: 220000,
  },
  {
    id: 4,
    title: 'As It Was',
    artists: [artistNames.harry_styles],
    features: [],
    coverUrl: '/as-it-was/cover.png',
    songUrl: '/as-it-was/song.mp3',
    lyricsUrl: '/as-it-was/lyrics.lrc',
    duration: 168000,
  },
  {
    id: 5,
    title: 'Watermelon Sugar',
    artists: [artistNames.harry_styles],
    features: [],
    coverUrl: '/watermelon/cover.png',
    songUrl: '/watermelon/song.mp3',
    lyricsUrl: '/watermelon/lyrics.lrc',
    duration: 174000,
  },
  {
    id: 6,
    title: 'Adore You',
    artists: [artistNames.harry_styles],
    features: [],
    coverUrl: '/adore-you/cover.png',
    songUrl: '/adore-you/song.mp3',
    lyricsUrl: '/adore-you/lyrics.lrc',
    duration: 208000,
  },
  {
    id: 7,
    title: 'Late Night Talking',
    artists: [artistNames.harry_styles],
    features: [],
    coverUrl: '/late-night-talking/cover.png',
    songUrl: '/late-night-talking/song.mp3',
    lyricsUrl: '/late-night-talking/lyrics.lrc',
    duration: 178000,
  },
  {
    id: 8,
    title: '1 Thing',
    artists: [artistNames.amerie],
    features: [],
    coverUrl: '/1-thing/cover.png',
    songUrl: '/1-thing/song.mp3',
    lyricsUrl: '/1-thing/lyrics.lrc',
    duration: 239000,
  },
  {
    id: 9,
    title: 'Save Your Tears',
    artists: [artistNames.the_weeknd],
    features: [],
    coverUrl: '/save-your-tears/cover.png',
    songUrl: '/save-your-tears/song.mp3',
    lyricsUrl: '/save-your-tears/lyrics.lrc',
    duration: 216000,
  },
  {
    id: 10,
    title: 'Childsplay',
    artists: [artistNames.iamddb],
    features: [],
    coverUrl: '/childs-play/cover.png',
    songUrl: '/childs-play/song.mp3',
    // lyricsUrl: '/childs-play/lyrics.lrc',
    duration: 226000,
  },
  {
    id: 11,
    title: 'Re:Re',
    artists: [artistNames.asian_kung_fu_generation],
    features: [],
    coverUrl: '/rere/cover.png',
    songUrl: '/rere/song.mp3',
    lyricsUrl: '/rere/lyrics.lrc',
    duration: 333000,
  },
  {
    id: 12,
    title: 'Seishun Kyousoukyoku',
    artists: [artistNames.asian_kung_fu_generation],
    features: [],
    coverUrl: '/seishun-kyousoukyoku/cover.png',
    songUrl: '/seishun-kyousoukyoku/song.mp3',
    lyricsUrl: '/seishun-kyousoukyoku/lyrics.lrc',
    duration: 287000,
  },
  {
    id: 13,
    title: '99',
    artists: [artistNames.mob_choir],
    features: [],
    coverUrl: '/99/cover.png',
    songUrl: '/99/song.mp3',
    lyricsUrl: '/99/lyrics.lrc',
    duration: 238000,
  },
  {
    id: 14,
    title: "Isabella's Lullaby",
    artists: [artistNames.sarah_alainn],
    features: [],
    coverUrl: '/isabella-lullaby/cover.jpeg',
    songUrl: '/isabella-lullaby/song.mp3',
    duration: 324000,
  },
  {
    id: 15,
    title: 'The Rumbling',
    artists: [artistNames.sim],
    features: [],
    coverUrl: '/Rumbling/cover.png',
    songUrl: '/Rumbling/song.mp3',
    lyricsUrl: '/Rumbling/lyrics.lrc',
    duration: 221000,
  },
  {
    id: 16,
    title: 'You Say Run',
    artists: [artistNames.mha],
    features: [],
    coverUrl: '/MHA/cover.png',
    songUrl: '/MHA/song.mp3',
    // lyricsUrl: '/MHA/lyrics.lrc',
    duration: 229000,
  },
  {
    id: 17,
    title: "Hero's Comeback",
    artists: [artistNames.nobody_knows],
    features: [],
    coverUrl: '/heros_comeback/cover.png',
    songUrl: '/heros_comeback/song.mp3',
    lyricsUrl: '/heros_comeback/lyrics.lrc',
    duration: 274000,
  },
  {
    id: 18,
    title: 'Harukamirai',
    artists: [artistNames.kankakupiero],
    features: [],
    coverUrl: '/harukamirai/cover.png',
    songUrl: '/harukamirai/song.mp3',
    lyricsUrl: '/harukamirai/lyrics.lrc',
    duration: 178000,
  },
  {
    id: 19,
    title: 'Gurenge',
    artists: [artistNames.lisa],
    features: [],
    coverUrl: '/gurenge/cover.png',
    songUrl: '/gurenge/song.mp3',
    lyricsUrl: '/gurenge/lyrics.lrc',
    duration: 338000,
  },
  {
    id: 20,
    title: 'Blood Circulator',
    artists: [artistNames.asian_kung_fu_generation],
    features: [],
    coverUrl: '/blood-circulator/cover.png',
    songUrl: '/blood-circulator/song.mp3',
    lyricsUrl: '/blood-circulator/lyrics.lrc',
    duration: 224000,
  },
  {
    id: 21,
    title: 'Again',
    artists: [artistNames.yui],
    features: [],
    coverUrl: '/again/cover.png',
    songUrl: '/again/song.mp3',
    lyricsUrl: '/again/lyrics.lrc',
    duration: 255000,
  },
  {
    id: 22,
    title: 'blue bird',
    artists: [artistNames.ikimonogakari],
    features: [],
    coverUrl: '/blue-bird/cover.png',
    songUrl: '/blue-bird/song.mp3',
    lyricsUrl: '/blue-bird/lyrics.lrc',
    duration: 219000,
  },
  {
    id: 23,
    title: 'The Day',
    artists: [artistNames.porno_graffitti],
    features: [],
    coverUrl: '/the-day/cover.png',
    songUrl: '/the-day/song.mp3',
    lyricsUrl: '/the-day/lyrics.lrc',
    duration: 241000,
  },
  {
    id: 24,
    title: 'Silhouette',
    artists: [artistNames.kana_boon],
    features: [],
    coverUrl: '/kana-boon/cover.jpg',
    songUrl: '/kana-boon/song.mp3',
    lyricsUrl: '/kana-boon/lyrics.lrc',
    duration: 241000,
  },
  {
    id: 25,
    title: 'GO!!!',
    artists: [artistNames.flow],
    features: [],
    coverUrl: '/go/cover.png',
    songUrl: '/go/song.mp3',
    lyricsUrl: '/go/lyrics.lrc',
    duration: 240000,
  },
  {
    id: 26,
    title: 'Distance',
    artists: [artistNames.long_shot_party],
    features: [],
    coverUrl: '/distance/cover.png',
    songUrl: '/distance/song.mp3',
    lyricsUrl: '/distance/lyrics.lrc',
    duration: 188000,
  },
  {
    id: 27,
    title: 'Specialz',
    artists: [artistNames.king_gnu],
    features: [],
    coverUrl: '/specials/cover.png',
    songUrl: '/specials/song.mp3',
    // lyricsUrl: '/specials/lyrics.lrc',
    duration: 240000,
  },
  {
    id: 28,
    title: 'January 28th',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/january-28/song.mp3',
    // lyricsUrl: '/2014/january-28/lyrics.lrc',
    duration: 243000,
  },
  {
    id: 29,
    title: 'Intro',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/intro/song.mp3',
    // lyricsUrl: '/2014/intro/lyrics.lrc',
    duration: 129000,
  },
  {
    id: 30,
    title: 'Wet Dreamz',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/wet-dreams/song.mp3',
    // lyricsUrl: '/2014/wet-dreams/lyrics.lrc',
    duration: 240000,
  },
  {
    id: 31,
    title: "03' Adolescence",
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/03-adolescence/song.mp3',
    // lyricsUrl: '/2014/03-adolescence/lyrics.lrc',
    duration: 265000,
  },
  {
    id: 32,
    title: 'A Tale of 2 Citiez',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/ATO2C/song.mp3',
    // lyricsUrl: '/2014/ATO2C/lyrics.lrc',
    duration: 270000,
  },
  {
    id: 33,
    title: 'Fire Squad',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/fire-squad/song.mp3',
    // lyricsUrl: '/2014/ATO2C/lyrics.lrc',
    duration: 289000,
  },
  {
    id: 34,
    title: 'St. Tropez',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/st-tropez/song.mp3',
    // lyricsUrl: '/2014/ATO2C/lyrics.lrc',
    duration: 258000,
  },
  {
    id: 35,
    title: 'G.O.M.D',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/gomd/song.mp3',
    // lyricsUrl: '/2014/ATO2C/lyrics.lrc',
    duration: 301000,
  },
  {
    id: 36,
    title: 'No Role Modelz',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/nrm/song.mp3',
    // lyricsUrl: '/2014/ATO2C/lyrics.lrc',
    duration: 273000,
  },
  {
    id: 37,
    title: 'Hello',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/hello/song.mp3',
    // lyricsUrl: '/2014/ATO2C/lyrics.lrc',
    duration: 219000,
  },
  {
    id: 38,
    title: 'Apparently',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/apparently/song.mp3',
    // lyricsUrl: '/2014/ATO2C/lyrics.lrc',
    duration: 273000,
  },
  {
    id: 39,
    title: 'Love Yourz',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/love-yours/song.mp3',
    // lyricsUrl: '/2014/ATO2C/lyrics.lrc',
    duration: 213000,
  },
  {
    id: 40,
    title: 'Note to Self',
    artists: [artistNames.j_cole],
    features: [],
    coverUrl: '/2014/cover.png',
    songUrl: '/2014/nts/song.mp3',
    // lyricsUrl: '/2014/ATO2C/lyrics.lrc',
    duration: 875000,
  },
];

export default songs;
