import { songType } from '../../types';
import { artistNames } from './artists';

const songs: songType[] = [
  {
    id: 0,
    title: 'Ni**as In Paris',
    artists: [artistNames.jayz, artistNames.kanye],
    features: [],
    coverUrl: '/african-americans-in-america/cover.png',
    songUrl: '/african-americans-in-america/song.mp3',
    lyricsUrl: '/african-americans-in-america/lyrics.lrc',
    duration: 232000,
  },
  {
    id: 1,
    title: 'Soul to Soul',
    artists: [],
    features: [],
    coverUrl: '/soul-to-soul.jpg',
    songUrl: '/soul-to-soul.mp3',
    duration: 481000,
  },
  {
    id: 2,
    title: 'Call Me Maybe',
    artists: [artistNames.carly_rae_Jepsen],
    features: [],
    coverUrl: '/call-me-maybe/cover.jpeg',
    songUrl: '/call-me-maybe/song.mp3',
    lyricsUrl: '/call-me-maybe/lyrics.lrc',
    duration: 194000,
  },
  {
    id: 3,
    title: 'Shake It Off',
    artists: [artistNames.taylor_swift],
    features: [],
    coverUrl: '/shake-it-off/cover.png',
    songUrl: '/shake-it-off/song.mp3',
    lyricsUrl: '/shake-it-off/lyrics.lrc',
    duration: 220000,
  },
  {
    id: 4,
    title: 'As It Was',
    artists: [artistNames.harry_styles],
    features: [],
    coverUrl: '/as-it-was/cover.png',
    songUrl: '/as-it-was/song.mp3',
    lyricsUrl: '/as-it-was/lyrics.lrc',
    duration: 168000,
  },
  {
    id: 5,
    title: 'Watermelon Sugar',
    artists: [artistNames.harry_styles],
    features: [],
    coverUrl: '/watermelon/cover.png',
    songUrl: '/watermelon/song.mp3',
    lyricsUrl: '/watermelon/lyrics.lrc',
    duration: 174000,
  },
  {
    id: 6,
    title: 'Adore You',
    artists: [artistNames.harry_styles],
    features: [],
    coverUrl: '/adore-you/cover.png',
    songUrl: '/adore-you/song.mp3',
    lyricsUrl: '/adore-you/lyrics.lrc',
    duration: 208000,
  },
  {
    id: 7,
    title: 'Late Night Talking',
    artists: [artistNames.harry_styles],
    features: [],
    coverUrl: '/late-night-talking/cover.png',
    songUrl: '/late-night-talking/song.mp3',
    lyricsUrl: '/late-night-talking/lyrics.lrc',
    duration: 178000,
  },
  {
    id: 8,
    title: '1 Thing',
    artists: [artistNames.amerie],
    features: [],
    coverUrl: '/1-thing/cover.png',
    songUrl: '/1-thing/song.mp3',
    lyricsUrl: '/1-thing/lyrics.lrc',
    duration: 239000,
  },
  {
    id: 9,
    title: 'Save Your Tears',
    artists: [artistNames.the_weeknd],
    features: [],
    coverUrl: '/save-your-tears/cover.png',
    songUrl: '/save-your-tears/song.mp3',
    lyricsUrl: '/save-your-tears/lyrics.lrc',
    duration: 216000,
  },
  {
    id: 10,
    title: 'Childsplay',
    artists: [artistNames.iamddb],
    features: [],
    coverUrl: '/childs-play/cover.png',
    songUrl: '/childs-play/song.mp3',
    // lyricsUrl: '/childs-play/lyrics.lrc',
    duration: 226000,
  },
  {
    id: 11,
    title: 'Re:Re',
    artists: [artistNames.asian_kung_fu_generation],
    features: [],
    coverUrl: '/rere/cover.png',
    songUrl: '/rere/song.mp3',
    lyricsUrl: '/rere/lyrics.lrc',
    duration: 333000,
  },
  {
    id: 12,
    title: 'Seishun Kyousoukyoku',
    artists: [artistNames.asian_kung_fu_generation],
    features: [],
    coverUrl: '/seishun-kyousoukyoku/cover.png',
    songUrl: '/seishun-kyousoukyoku/song.mp3',
    lyricsUrl: '/seishun-kyousoukyoku/lyrics.lrc',
    duration: 287000,
  },
  {
    id: 13,
    title: '99',
    artists: [artistNames.mob_choir],
    features: [],
    coverUrl: '/99/cover.png',
    songUrl: '/99/song.mp3',
    lyricsUrl: '/99/lyrics.lrc',
    duration: 238000,
  },
  {
    id: 14,
    title: "Isabella's Lullaby",
    artists: [artistNames.sarah_alainn],
    features: [],
    coverUrl: '/isabella-lullaby/cover.jpeg',
    songUrl: '/isabella-lullaby/song.mp3',
    duration: 324000,
  },
  {
    id: 15,
    title: 'The Rumbling',
    artists: [artistNames.sim],
    features: [],
    coverUrl: '/Rumbling/cover.png',
    songUrl: '/Rumbling/song.mp3',
    lyricsUrl: '/Rumbling/lyrics.lrc',
    duration: 221000,
  },
  {
    id: 16,
    title: 'You Say Run',
    artists: [artistNames.mha],
    features: [],
    coverUrl: '/MHA/cover.png',
    songUrl: '/MHA/song.mp3',
    // lyricsUrl: '/MHA/lyrics.lrc',
    duration: 229000,
  },
  {
    id: 17,
    title: "Hero's Comeback",
    artists: [artistNames.nobody_knows],
    features: [],
    coverUrl: '/heros_comeback/cover.png',
    songUrl: '/heros_comeback/song.mp3',
    lyricsUrl: '/heros_comeback/lyrics.lrc',
    duration: 274000,
  },
  {
    id: 18,
    title: 'Harukamirai',
    artists: [artistNames.kankakupiero],
    features: [],
    coverUrl: '/harukamirai/cover.png',
    songUrl: '/harukamirai/song.mp3',
    lyricsUrl: '/harukamirai/lyrics.lrc',
    duration: 178000,
  },
  {
    id: 19,
    title: 'Gurenge',
    artists: [artistNames.lisa],
    features: [],
    coverUrl: '/gurenge/cover.png',
    songUrl: '/gurenge/song.mp3',
    lyricsUrl: '/gurenge/lyrics.lrc',
    duration: 338000,
  },
  {
    id: 20,
    title: 'Blood Circulator',
    artists: [artistNames.asian_kung_fu_generation],
    features: [],
    coverUrl: '/blood-circulator/cover.png',
    songUrl: '/blood-circulator/song.mp3',
    lyricsUrl: '/blood-circulator/lyrics.lrc',
    duration: 224000,
  },
  {
    id: 21,
    title: 'Again',
    artists: [artistNames.yui],
    features: [],
    coverUrl: '/again/cover.png',
    songUrl: '/again/song.mp3',
    lyricsUrl: '/again/lyrics.lrc',
    duration: 255000,
  },
];

export default songs;
