import { songType } from '../../types';

const songs: songType[] = [
  {
    id: 0,
    title: 'Ni**as In Paris',
    artists: [
      { name: 'Jay-Z', link: 'https://en.wikipedia.org/wiki/Jay-Z' },
      {
        name: 'Kanye West',
        link: 'https://en.wikipedia.org/wiki/Kanye_West',
      },
    ],
    features: [],
    coverUrl: '/african-americans-in-america/cover.png',
    songUrl: '/african-americans-in-america/song.mp3',
    lyricsUrl: '/african-americans-in-america/lyrics.lrc',
    duration: 232000,
  },
  {
    id: 1,
    title: 'Soul to Soul',
    artists: [{ name: 'Kelvin Momo' }],
    features: [],
    coverUrl: '/soul-to-soul.jpg',
    songUrl: '/soul-to-soul.mp3',
    duration: 481000,
  },
  {
    id: 2,
    title: 'Call Me Maybe',
    artists: [{ name: 'Carly Rae Jepsen' }],
    features: [],
    coverUrl: '/call-me-maybe/cover.jpeg',
    songUrl: '/call-me-maybe/song.mp3',
    lyricsUrl: '/call-me-maybe/lyrics.lrc',
    duration: 194000,
  },
  {
    id: 3,
    title: 'Shake It Off',
    artists: [{ name: 'Taylor Swift' }],
    features: [],
    coverUrl: '/shake-it-off/cover.png',
    songUrl: '/shake-it-off/song.mp3',
    lyricsUrl: '/shake-it-off/lyrics.lrc',
    duration: 220000,
  },
  {
    id: 4,
    title: 'As It Was',
    artists: [{ name: 'Harry Styles' }],
    features: [],
    coverUrl: '/as-it-was/cover.png',
    songUrl: '/as-it-was/song.mp3',
    lyricsUrl: '/as-it-was/lyrics.lrc',
    duration: 168000,
  },
  {
    id: 5,
    title: 'Watermelon Sugar',
    artists: [{ name: 'Harry Styles' }],
    features: [],
    coverUrl: '/watermelon/cover.png',
    songUrl: '/watermelon/song.mp3',
    lyricsUrl: '/watermelon/lyrics.lrc',
    duration: 174000,
  },
  {
    id: 6,
    title: 'Adore You',
    artists: [{ name: 'Harry Styles' }],
    features: [],
    coverUrl: '/adore-you/cover.png',
    songUrl: '/adore-you/song.mp3',
    lyricsUrl: '/adore-you/lyrics.lrc',
    duration: 208000,
  },
  {
    id: 7,
    title: 'Late Night Talking',
    artists: [{ name: 'Harry Styles' }],
    features: [],
    coverUrl: '/late-night-talking/cover.png',
    songUrl: '/late-night-talking/song.mp3',
    lyricsUrl: '/late-night-talking/lyrics.lrc',
    duration: 178000,
  },
  {
    id: 8,
    title: '1 Thing',
    artists: [{ name: 'Amerie' }],
    features: [],
    coverUrl: '/1-thing/cover.png',
    songUrl: '/1-thing/song.mp3',
    lyricsUrl: '/1-thing/lyrics.lrc',
    duration: 239000,
  },
  {
    id: 9,
    title: 'Save Your Tears',
    artists: [{ name: 'The Weeknd' }],
    features: [],
    coverUrl: '/save-your-tears/cover.png',
    songUrl: '/save-your-tears/song.mp3',
    lyricsUrl: '/save-your-tears/lyrics.lrc',
    duration: 216000,
  },
  {
    id: 10,
    title: 'Childsplay',
    artists: [{ name: 'IAMDDB' }],
    features: [],
    coverUrl: '/childs-play/cover.png',
    songUrl: '/childs-play/song.mp3',
    // lyricsUrl: '/childs-play/lyrics.lrc',
    duration: 226000,
  },
  {
    id: 11,
    title: 'Re:Re',
    artists: [{ name: 'ASIAN KUNG-FU GENERATION - リライト' }],
    features: [],
    coverUrl: '/rere/cover.png',
    songUrl: '/rere/song.mp3',
    lyricsUrl: '/rere/lyrics.lrc',
    duration: 333000,
  },
  {
    id: 12,
    title: 'Seishun Kyousoukyoku',
    artists: [{ name: 'ASIAN KUNG-FU GENERATION - リライト' }],
    features: [],
    coverUrl: '/seishun-kyousoukyoku/cover.png',
    songUrl: '/seishun-kyousoukyoku/song.mp3',
    lyricsUrl: '/seishun-kyousoukyoku/lyrics.lrc',
    duration: 287000,
  },
  {
    id: 13,
    title: '99',
    artists: [{ name: 'MOB CHOIR' }],
    features: [],
    coverUrl: '/99/cover.png',
    songUrl: '/99/song.mp3',
    lyricsUrl: '/99/lyrics.lrc',
    duration: 238000,
  },
  {
    id: 14,
    title: "Isabella's Lullaby",
    artists: [{ name: 'Sarah Àlainn' }],
    features: [],
    coverUrl: '/isabella-lullaby/cover.jpeg',
    songUrl: '/isabella-lullaby/song.mp3',
    duration: 324000,
  },
];

export default songs;
